# -*- coding: utf-8 -*-
"""stat project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Zd2bvJwkuKwDn1Y1GC3lN9Cn4o6j5ru5
"""

# ============================================
# 1. SETUP: IMPORT LIBRARIES
# ============================================

import kagglehub
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

plt.rcParams["figure.figsize"] = (8, 5)
plt.rcParams["axes.grid"] = True
sns.set_style("whitegrid")


# ============================================
# 2. DOWNLOAD DATASET USING KAGGLEHUB
# ============================================

dataset_path = kagglehub.dataset_download(
    "mahdimashayekhi/social-media-vs-productivity"
)

print("Path to dataset files:", dataset_path)


# ============================================
# 3. LOAD CSV FILE
# ============================================

# List files inside dataset folder
import os
print("Files in dataset folder:", os.listdir(dataset_path))

# Load the CSV file
csv_path = os.path.join(dataset_path, "social_media_vs_productivity.csv")
df = pd.read_csv(csv_path)

print("Data loaded. Shape:", df.shape)


# ============================================
# 4. RENAME COLUMNS
# ============================================

df = df.rename(columns={
    "daily_social_media_time": "social_media_time",
    "actual_productivity_score": "productivity",
    "stress_level": "stress",
    "coffee_consumption_per_day": "coffee_intake",
    "days_feeling_burnout_per_month": "burnout_days",
})

cols_needed = [
    "social_media_time",
    "productivity",
    "stress",
    "gender",
    "sleep_hours",
    "coffee_intake",
    "burnout_days",
    "number_of_notifications",
    "work_hours_per_day",
    "screen_time_before_sleep",
    "weekly_offline_hours",
]

data = df[cols_needed].copy()


# ============================================
# 5. HANDLE MISSING VALUES
# ============================================

data = data.dropna(subset=[
    "social_media_time",
    "productivity",
    "stress",
    "gender",
    "sleep_hours",
    "coffee_intake",
    "burnout_days"
])

print("Shape after cleaning:", data.shape)


# ============================================
# 6. CLEAN GENDER VARIABLE
# ============================================

data["gender"] = (
    data["gender"]
    .astype(str)
    .str.strip()
    .str.title()
)


# ============================================
# 7. DEFINE NUMERICAL VARIABLES
# ============================================

numerical_vars = [
    "social_media_time",
    "productivity",
    "stress",
    "sleep_hours",
    "coffee_intake",
    "burnout_days",
]


# ============================================
# 8. BOXPLOTS
# ============================================

x_labels = [
    "Social media time (hours/day)",
    "Productivity score (0–10)",
    "Stress level (1–10)",
    "Sleep hours (hours/night)",
    "Coffee intake (cups/day)",
    "Burnout days (days/month)",
]

plt.figure(figsize=(12, 6))
ax = sns.boxplot(data=data[numerical_vars], color="#1f77b4")

ax.set_xlabel("Variables (with units)")
ax.set_ylabel("Observed value")
ax.set_xticklabels(x_labels, rotation=20, ha="right")

plt.tight_layout()
plt.show()


# ============================================
# 9. HISTOGRAMS
# ============================================

fig, axes = plt.subplots(3, 2, figsize=(12, 9))
axes = axes.flatten()

labels = {
    "social_media_time": "Daily social media time (hours)",
    "productivity": "Productivity score (0–10)",
    "stress": "Stress level (1–10)",
    "sleep_hours": "Sleep hours per night",
    "coffee_intake": "Coffee intake (cups per day)",
    "burnout_days": "Burnout days per month",
}

for ax, var in zip(axes, numerical_vars):
    ax.hist(
        data[var],
        bins=20,
        color="#1f77b4",
        edgecolor="black"
    )
    ax.set_xlabel(labels[var])
    ax.set_ylabel("Frequency")

plt.tight_layout()
plt.show()


# ============================================
# 10. CORRELATION MATRIX
# ============================================

corr = data[numerical_vars].corr()

plt.figure(figsize=(7, 5))
sns.heatmap(
    corr,
    annot=True,
    cmap="Blues",
    fmt=".2f",
    linewidths=0.5
)

plt.xlabel("Variables")
plt.ylabel("Variables")
plt.tight_layout()
plt.show()

print("EDA completed successfully.")

# ============================================================
# Q1 — EFFECT OF SOCIAL MEDIA TIME ON PRODUCTIVITY
# ============================================================

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

from scipy import stats
import statsmodels.api as sm

print("============================================")
print("Q1: Social Media Time → Productivity")
print("============================================\n")

# ------------------------------------------------------------
# 1. CORRELATION ANALYSIS
# ------------------------------------------------------------

prod_corr, prod_p = stats.pearsonr(
    data["social_media_time"],
    data["productivity"]
)

print("📌 Correlation Result:")
print(f"   • Social Media Time ↔ Productivity : r = {prod_corr:.4f}, p = {prod_p:.4e}\n")

# ------------------------------------------------------------
# 2. SCATTERPLOT WITH REGRESSION LINE
# ------------------------------------------------------------

plt.figure(figsize=(7, 5))

sns.regplot(
    x="social_media_time",
    y="productivity",
    data=data,
    scatter_kws={"alpha": 0.25, "s": 20},
    line_kws={"color": "red", "linewidth": 2}
)

plt.title("Daily Social Media Usage vs Productivity", fontsize=12)
plt.xlabel("Daily social media usage (hours/day)", fontsize=11)
plt.ylabel("Productivity score (0–10)", fontsize=11)

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 3. SIMPLE LINEAR REGRESSION (PRODUCTIVITY)
# ------------------------------------------------------------

X = sm.add_constant(data["social_media_time"])
y = data["productivity"]

model = sm.OLS(y, X).fit()

print("\n==============================")
print("Regression: Productivity Model")
print("==============================")
print(model.summary())

# ------------------------------------------------------------
# 4. RESIDUAL DIAGNOSTICS
# ------------------------------------------------------------

plt.figure(figsize=(6, 4))

sns.residplot(
    x=model.fittedvalues,
    y=model.resid,
    lowess=True
)

plt.title("Residuals vs Fitted Values (Productivity Model)")
plt.xlabel("Fitted values")
plt.ylabel("Residuals")

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 5. FINAL INTERPRETATION SUMMARY
# ------------------------------------------------------------

print("\n======================================================")
print("Q1 — INTERPRETATION SUMMARY")
print("======================================================")

if prod_p < 0.05:
    effect = "decreases" if prod_corr < 0 else "increases"
    print(f"✔ Social media time significantly {effect} productivity "
          f"(r = {prod_corr:.3f}, p < 0.05).")
else:
    print(f"✔ No statistically significant relationship between social media time "
          f"and productivity (r = {prod_corr:.3f}, p = {prod_p:.4f}).")

print("======================================================")
print("End of Q1")
print("======================================================")

# ============================================================
# Q2 — GENDER DIFFERENCES IN PRODUCTIVITY
# ============================================================

print("============================================")
print("Q2: Gender differences in productivity")
print("============================================\n")

# ------------------------------------------------------------
# 0. REQUIRED IMPORTS (SAFE TO KEEP)
# ------------------------------------------------------------

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# ------------------------------------------------------------
# 1. PREPARE GROUPS
# ------------------------------------------------------------

# Keep only Male / Female
mask = data["gender"].isin(["Male", "Female"])
q2_data = data[mask].copy()

group_m = q2_data[q2_data["gender"] == "Male"]["productivity"]
group_f = q2_data[q2_data["gender"] == "Female"]["productivity"]

print(f"Sample size (Male)   : n = {len(group_m)}")
print(f"Sample size (Female) : n = {len(group_f)}\n")

print("Group means and std:")
print(f"  Male   → mean = {group_m.mean():.3f}, std = {group_m.std(ddof=1):.3f}")
print(f"  Female → mean = {group_f.mean():.3f}, std = {group_f.std(ddof=1):.3f}\n")

# ------------------------------------------------------------
# 2. TWO-SAMPLE T-TEST (WELCH)
# ------------------------------------------------------------

t_stat, p_val = stats.ttest_ind(group_m, group_f, equal_var=False)

print("📌 Welch Two-sample t-test (Productivity by Gender)")
print(f"   t-statistic = {t_stat:.3f}")
print(f"   p-value     = {p_val:.4e}\n")

# ------------------------------------------------------------
# 3. EFFECT SIZE (COHEN'S d)
# ------------------------------------------------------------

mean_m = group_m.mean()
mean_f = group_f.mean()

std_pooled = np.sqrt(
    ((len(group_m) - 1) * group_m.var(ddof=1) +
     (len(group_f) - 1) * group_f.var(ddof=1)) /
    (len(group_m) + len(group_f) - 2)
)

cohen_d = (mean_m - mean_f) / std_pooled

print("📌 Effect size (Cohen's d)")
print(f"   d = {cohen_d:.3f}")

if abs(cohen_d) < 0.2:
    print("   → Very small / negligible difference.")
elif abs(cohen_d) < 0.5:
    print("   → Small effect.")
elif abs(cohen_d) < 0.8:
    print("   → Medium effect.")
else:
    print("   → Large effect.")
print()

# ------------------------------------------------------------
# 4. VISUALIZATIONS (CLEAN & BLUE ONLY)
# ------------------------------------------------------------

fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# ---- Boxplot ----
sns.boxplot(
    x="gender",
    y="productivity",
    data=q2_data,
    ax=ax[0],
    color="#1f77b4"
)

ax[0].set_title("Productivity by Gender (Boxplot)", fontsize=12)
ax[0].set_xlabel("Gender", fontsize=11)
ax[0].set_ylabel("Productivity score (0–10)", fontsize=11)

# ---- Violin plot with box inside ----
sns.violinplot(
    x="gender",
    y="productivity",
    data=q2_data,
    ax=ax[1],
    inner="box",
    cut=0,
    color="#1f77b4"
)

ax[1].set_title("Productivity Distribution by Gender", fontsize=12)
ax[1].set_xlabel("Gender", fontsize=11)
ax[1].set_ylabel("Productivity score (0–10)", fontsize=11)

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 5. INTERPRETATION SUMMARY
# ------------------------------------------------------------

print("======================================================")
print("Q2 — INTERPRETATION SUMMARY")
print("======================================================")

alpha = 0.05

if p_val < alpha:
    higher_group = "Male" if mean_m > mean_f else "Female"
    diff = abs(mean_m - mean_f)
    print(f"✔ The difference in mean productivity between genders is statistically significant (p < {alpha}).")
    print(f"  • {higher_group} group has the higher average productivity.")
    print(f"  • Mean difference ≈ {diff:.3f} points.")
else:
    print(f"✔ The t-test does NOT find a statistically significant difference in mean productivity between genders "
          f"(p = {p_val:.4f} ≥ {alpha}).")
    print("  → Any observed difference in sample means could be due to random variation.")

print(f"\nEffect size (Cohen's d) = {cohen_d:.3f}.")
print("======================================================")
print("End of Q2")
print("======================================================")

# ============================================================
# Q3 — JOB SATISFACTION → PRODUCTIVITY
# ============================================================

import statsmodels.api as sm2

print("============================================")
print("Q3: Job Satisfaction → Productivity")
print("============================================\n")

# ------------------------------------------------------------
# 1. SELECT VARIABLES
# ------------------------------------------------------------

paired = df[["job_satisfaction_score", "productivity"]].dropna()

# ------------------------------------------------------------
# 2. CORRELATION
# ------------------------------------------------------------

corr, p_val = stats.pearsonr(
    paired["job_satisfaction_score"],
    paired["productivity"]
)

print(f"📌 Correlation: r = {corr:.4f}, p = {p_val:.4e}\n")

# ------------------------------------------------------------
# 3. SCATTERPLOT
# ------------------------------------------------------------

sns.regplot(
    x="job_satisfaction_score",
    y="productivity",
    data=paired,
    scatter_kws={"alpha": 0.2, "s": 15},
    line_kws={"color": "blue", "linewidth": 2}
)

plt.title("Job Satisfaction vs Productivity")
plt.xlabel("Job satisfaction score (0–10)")
plt.ylabel("Productivity score (0–10)")

plt.show()

# ------------------------------------------------------------
# 4. REGRESSION MODEL
# ------------------------------------------------------------

X = sm2.add_constant(paired["job_satisfaction_score"])
y = paired["productivity"]

model = sm2.OLS(y, X).fit()
print(model.summary())

# ------------------------------------------------------------
# 5. INTERPRETATION SUMMARY
# ------------------------------------------------------------

print("\n============================================")
print("Q3 — INTERPRETATION SUMMARY")
print("============================================")

if p_val < 0.05:
    print("✔ Job satisfaction significantly predicts productivity (p < 0.05).")

    if corr > 0:
        print("  → Higher job satisfaction is associated with HIGHER productivity.")
    else:
        print("  → Higher job satisfaction is associated with LOWER productivity (unexpected).")

    print(f"  → Effect size: r = {corr:.3f}")
else:
    print("✘ No significant relationship found between job satisfaction and productivity.")

print("============================================")
print("End of Q3")
print("============================================")

# ============================================================
# Q4 — MULTIPLE REGRESSION
# Lifestyle Factors → Productivity
# ============================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
from statsmodels.stats.outliers_influence import variance_inflation_factor

print("============================================")
print("Q4: Lifestyle factors predicting productivity")
print("============================================\n")

# ------------------------------------------------------------
# 1. SELECT VARIABLES
# ------------------------------------------------------------

predictors = [
    "social_media_time",
    "sleep_hours",
    "coffee_intake",
    "burnout_days",
    "stress"
]

X = data[predictors].copy()
y = data["productivity"]

# Add intercept
X_const = sm.add_constant(X)

# ------------------------------------------------------------
# 2. FIT MULTIPLE REGRESSION MODEL
# ------------------------------------------------------------

model_multi = sm.OLS(y, X_const).fit()

print("\n==============================")
print("MULTIPLE REGRESSION SUMMARY")
print("==============================")
print(model_multi.summary())

# ------------------------------------------------------------
# 3. REGRESSION RESULTS TABLE (FOR REPORT)
# ------------------------------------------------------------

regression_table = pd.DataFrame({
    "Predictor": model_multi.params.index,
    "Coefficient": model_multi.params.values,
    "Std. Error": model_multi.bse.values,
    "p-value": model_multi.pvalues.values
})

# Remove intercept from table (optional, cleaner for report)
regression_table = regression_table[regression_table["Predictor"] != "const"]

print("\n==============================")
print("REGRESSION RESULTS TABLE")
print("==============================")
print(regression_table.round(4))

# ------------------------------------------------------------
# 4. MULTICOLLINEARITY CHECK (VIF)
# ------------------------------------------------------------

vif_df = pd.DataFrame()
vif_df["Predictor"] = X.columns
vif_df["VIF"] = [
    variance_inflation_factor(X.values, i)
    for i in range(X.shape[1])
]

print("\n==============================")
print("VARIANCE INFLATION FACTORS (VIF)")
print("==============================")
print(vif_df.round(3))

# ------------------------------------------------------------
# 5. RESIDUAL DIAGNOSTICS
# ------------------------------------------------------------

fig, ax = plt.subplots(1, 2, figsize=(14, 5))

# Residuals vs Fitted
sns.residplot(
    x=model_multi.fittedvalues,
    y=model_multi.resid,
    lowess=True,
    scatter_kws={"alpha": 0.4},
    ax=ax[0]
)
ax[0].set_title("Residuals vs Fitted")
ax[0].set_xlabel("Fitted Productivity")
ax[0].set_ylabel("Residuals")

# QQ Plot
sm.qqplot(model_multi.resid, line="45", ax=ax[1])
ax[1].set_title("Q-Q Plot of Residuals")

plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 6. MODEL FIT SUMMARY (NUMBERS ONLY)
# ------------------------------------------------------------

print("\n==============================")
print("MODEL FIT")
print("==============================")
print(f"R-squared       : {model_multi.rsquared:.4f}")
print(f"Adjusted R²     : {model_multi.rsquared_adj:.4f}")
print("======================================================")

# ============================================================
# Q5 — PCA + K-MEANS CLUSTERING (Behavior Groups)
# ============================================================

print("============================================")
print("Q5: Clustering Users by Behavioral Patterns")
print("============================================\n")

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# ------------------------------------------------------------
# 1. SELECT FEATURES FOR CLUSTERING
# ------------------------------------------------------------

cluster_vars = [
    "social_media_time",
    "productivity",
    "stress",
    "sleep_hours",
    "burnout_days",
    "coffee_intake"
]

X = data[cluster_vars].copy()

print("Variables selected for clustering:")
for v in cluster_vars:
    print(" •", v)
print("\n")

# ------------------------------------------------------------
# 2. STANDARDIZE DATA
# ------------------------------------------------------------

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("✔ Data standardized using StandardScaler.\n")

# ------------------------------------------------------------
# 3. PCA (REDUCE TO 2 COMPONENTS FOR VISUALIZATION)
# ------------------------------------------------------------

pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print("PCA Explained Variance:")
print(f" • PC1: {pca.explained_variance_ratio_[0]:.3f}")
print(f" • PC2: {pca.explained_variance_ratio_[1]:.3f}\n")

# ------------------------------------------------------------
# 4. K-MEANS CLUSTERING (K=3)
# ------------------------------------------------------------

kmeans = KMeans(n_clusters=3, n_init=10, random_state=42)
clusters = kmeans.fit_predict(X_pca)

data["cluster"] = clusters

print("✔ K-Means applied with k = 3 clusters.\n")

# ------------------------------------------------------------
# 5. VISUALIZATION OF CLUSTERS
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

sns.scatterplot(
    x=X_pca[:, 0],
    y=X_pca[:, 1],
    hue=[f"Cluster {c}" for c in clusters],
    palette="viridis",
    s=35,
    alpha=0.6
)

plt.title("PCA Clusters (K=3)")
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.legend(title="Cluster")
plt.tight_layout()
plt.show()

# ------------------------------------------------------------
# 6. CLUSTER CENTROIDS (IN ORIGINAL VARIABLE SPACE)
# ------------------------------------------------------------

centroids_scaled = kmeans.cluster_centers_
centroids_original = scaler.inverse_transform(
    pca.inverse_transform(centroids_scaled)
)

centroid_df = pd.DataFrame(
    centroids_original, columns=cluster_vars
)

print("======================================================")
print("CLUSTER CENTROIDS (Approximate Profile for Each Group)")
print("======================================================")
print(centroid_df)
print("\n")

# ------------------------------------------------------------
# 7. INTERPRETATION SUMMARY
# ------------------------------------------------------------

print("======================================================")
print("Q5 — INTERPRETATION SUMMARY")
print("======================================================")

for i in range(3):
    print(f"\nCluster {i}:")
    row = centroid_df.loc[i]

    # Behavioral interpretation
    if row["social_media_time"] > centroid_df["social_media_time"].mean():
        sm = "High social media use"
    else:
        sm = "Low/Moderate social media use"

    if row["productivity"] > centroid_df["productivity"].mean():
        prod = "High productivity"
    else:
        prod = "Lower productivity"

    if row["stress"] > centroid_df["stress"].mean():
        stress_tag = "High stress"
    else:
        stress_tag = "Low stress"

    if row["burnout_days"] > centroid_df["burnout_days"].mean():
        burn = "Burnout-prone"
    else:
        burn = "Balanced burnout levels"

    print(f"  • {sm}")
    print(f"  • {prod}")
    print(f"  • {stress_tag}")
    print(f"  • {burn}")

print("\n======================================================")
print("End of Q5")
print("======================================================")
